"""Turn the hybrid study JSON into the markdown reports under results/hybrid/.

Kept separate from the studies themselves so the reports can be regenerated,
and their tables re-cut, without re-running any training.

Usage (from src/hybrid):
    python write_reports.py --results-dir ../../results/hybrid
"""

from __future__ import annotations

import argparse
import glob
import json
import statistics
from pathlib import Path

SOLVER_ORDER = [
    "euler_dt0.08",
    "euler_dt0.02",
    "euler_dt0.005",
    "rk45_tol1e-2",
    "rk45_tol1e-3",
    "rk45_tol1e-4",
    "rk45_T4x",
    "rk45_T16x",
    "rk45_T64x",
]

CONTROL_ORDER = [
    "euler_original_T6.4",
    "euler_dt0.08",
    "euler_dt0.02",
    "euler_dt0.005",
    "rk45_tol1e-3",
    "rk45_T4x",
]

READOUT_LABELS = {
    "linear": "Linear soft-max",
    "phase_uncoupled": "Phase readout, uncoupled (K = 0)",
    "phase_coupled": "Phase readout, coupled",
}


def mean_std(values):
    values = list(values)
    if not values:
        return float("nan"), float("nan")
    if len(values) == 1:
        return values[0], 0.0
    return statistics.mean(values), statistics.stdev(values)


def write_relaxation_report(results_dir: Path, out_path: Path) -> None:
    payload = json.loads(
        (results_dir / "relaxation" / "relaxation_study.json").read_text()
    )
    rows = payload["solver_sweep"]

    controls = {}
    for path in glob.glob(str(results_dir / "relaxation" / "training_controls*.json")):
        controls.update(json.loads(Path(path).read_text())["controls"])

    lines = [
        "# How accurately must the readout relax for EP to work?",
        "",
        "Generated by `src/hybrid/relaxation_study.py` and",
        "`src/hybrid/training_controls.py`; tables cut by",
        "`src/hybrid/write_reports.py`. Seed "
        f"{payload['seed']}, {payload['test_samples']}-sample test partition,",
        f"{payload['feature_dim']}-dimensional cached FHN features.",
        "",
        "## 1. Fixed weights, varying solver",
        "",
        "Training checkpoints are reloaded and the weights and inputs held fixed,",
        "so these rows measure inference only. `R` is the per-sample residual",
        "‖∂E/∂φ‖₂ at the end of the relaxation; `frac<1e-3` is the fraction of",
        "samples meeting the stopping criterion the manuscript states; `evals`",
        "counts right-hand-side evaluations (free + nudged).",
        "",
        "| checkpoint | solver | T | accuracy | R mean | R median | R p95 | frac<1e-3 | evals | s |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]

    by_key = {}
    for row in rows:
        by_key.setdefault((row["stage"], row["solver"]), {})[row["phase"]] = row

    for stage in ("early", "middle", "final"):
        for solver in SOLVER_ORDER:
            entry = by_key.get((stage, solver))
            if entry is None:
                continue
            free, nudged = entry["free"], entry["nudged"]
            lines.append(
                f"| {stage} | `{solver}` | ×{free['time_scale']:g} "
                f"| {free['accuracy']:.4f} "
                f"| {free['residual_mean']:.2e} "
                f"| {free['residual_median']:.2e} "
                f"| {free['residual_p95']:.2e} "
                f"| {free['fraction_below']['1e-03']:.3f} "
                f"| {free['rhs_evaluations'] + nudged['rhs_evaluations']} "
                f"| {free['seconds'] + nudged['seconds']:.1f} |"
            )

    mechanism = payload.get("mechanism", {})
    probe = payload.get("batch_size_probe", [])

    lines += [
        "",
        "## 2. Why the residuals exceed the stated threshold",
        "",
        "Two effects, measured separately.",
        "",
        "**The relaxation runs out of time, not out of accuracy.** Tightening the",
        "RK45 local tolerance from 1e-2 to 1e-4 leaves the terminal residual",
        "unchanged, and refining the Euler step by 16× (0.08 → 0.005) does not",
        "help either. Multiplying the *time budget* by four drops the residual by",
        "two orders of magnitude and is the only change that lets the stated",
        "criterion R < 1e-3 actually be met.",
        "",
        "**The criterion is imposed on a batch mean.** `EnergyOscillatorHead`",
        "stops when the mean residual over the batch falls below the tolerance, so",
        "a batch can stop while individual samples are far from equilibrium.",
        "",
    ]

    if probe:
        lines += [
            "| batch size | accuracy | R mean | batch-mean R | frac<1e-3 | s |",
            "|---|---|---|---|---|---|",
        ]
        for row in probe:
            lines.append(
                f"| {row['batch_size']} | {row['accuracy']:.4f} "
                f"| {row['residual_mean']:.2e} | {row['batch_mean_residual']:.2e} "
                f"| {row['fraction_below']['1e-03']:.3f} | {row['seconds']:.1f} |"
            )
        lines.append("")

    if mechanism:
        lines += [
            "**Which samples stall.** Linearising the energy about its minimum",
            "makes the field magnitude r_c = √(a_c² + b_c²) the relaxation *rate*",
            "of class c, so r_c·T is the number of e-foldings available. Samples",
            "that fail to converge are the weak-field ones:",
            "",
            f"- Spearman(slowest rate, residual) = "
            f"{mechanism['spearman_slowest_rate_vs_residual']:+.3f}",
            f"- median slowest rate, converged samples: "
            f"{mechanism['slowest_rate_of_converged_median']:.3f}",
            f"- median slowest rate, unconverged samples: "
            f"{mechanism['slowest_rate_of_unconverged_median']:.3f}",
            f"- fraction of samples with r_min·T < 10: "
            f"{mechanism['fraction_with_rate_times_T_below_10']:.3f}",
            "",
        ]

    if controls:
        lines += [
            "## 3. Training controls: does the solver change *learning*?",
            "",
            "Section 1 holds the weights fixed, so it cannot show that the solver",
            "changes what is learned. Here the same readout is trained from an",
            "identical initialisation on identical features under each scheme.",
            "`T` is the relaxation budget: ×1 is the 16 time units the adaptive",
            "driver uses, ×0.4 the 6.4 units of the `EnergyOscillatorHead` class",
            "defaults that the original fixed-step experiment inherited.",
            "",
            "| control | T | best acc | peak epoch | final acc | drop from peak | max residual |",
            "|---|---|---|---|---|---|---|",
        ]
        for label in CONTROL_ORDER:
            entry = controls.get(label)
            if entry is None:
                continue
            lines.append(
                f"| `{label}` | ×{entry['time_scale']:g} "
                f"| {entry['best_accuracy']:.4f} | {entry['peak_epoch']} "
                f"| {entry['final_accuracy']:.4f} "
                f"| {entry['accuracy_drop_from_peak']:+.4f} "
                f"| {entry['residual_max']:.4f} |"
            )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")


def write_ablation_report(results_dir: Path, out_path: Path) -> None:
    merged = {}
    for path in sorted(glob.glob(str(results_dir / "ablation_seed*" / "readout_ablation.json"))):
        blob = json.loads(Path(path).read_text())
        for seed, entry in blob["per_seed"].items():
            merged[int(seed)] = entry
    if not merged:
        print("no ablation results found, skipping")
        return

    seeds = sorted(merged)
    readouts = [r for r in READOUT_LABELS if r in merged[seeds[0]]]

    lines = [
        "# Do the output-oscillator interactions help?",
        "",
        "Generated by `src/hybrid/readout_ablation.py`; tables cut by",
        "`src/hybrid/write_reports.py`. Seeds "
        f"{', '.join(str(s) for s in seeds)}, each sharing one cached FHN feature",
        "set and one train/validation/test split across all three readouts.",
        "Epochs are selected on the validation split, never on the test set.",
        "",
        "| readout | test accuracy | errors/360 | parameters (stored/effective) | ms/sample |",
        "|---|---|---|---|---|",
    ]
    for name in readouts:
        accuracy_mean, accuracy_std = mean_std(
            merged[s][name]["accuracy"] for s in seeds
        )
        error_mean, _ = mean_std(merged[s][name]["errors"] for s in seeds)
        milliseconds, _ = mean_std(
            merged[s][name]["seconds_per_sample"] * 1e3 for s in seeds
        )
        stored = merged[seeds[0]][name]["stored_parameters"]
        effective = merged[seeds[0]][name]["effective_parameters"]
        lines.append(
            f"| {READOUT_LABELS[name]} | {accuracy_mean:.4f} ± {accuracy_std:.4f} "
            f"| {error_mean:.1f} | {stored} / {effective} | {milliseconds:.3f} |"
        )

    lines += [
        "",
        "## Paired differences",
        "",
        "The seeds share their features and splits, so the comparison is paired",
        "and the per-seed spread is the relevant scale. Five paired runs support",
        "a statement about the observed difference and its dispersion; they are",
        "not enough to claim statistical equivalence, and none is claimed.",
        "",
        "| comparison | mean difference | std | per-seed | wins |",
        "|---|---|---|---|---|",
    ]
    for i, first in enumerate(readouts):
        for second in readouts[i + 1 :]:
            differences = [
                merged[s][second]["accuracy"] - merged[s][first]["accuracy"]
                for s in seeds
            ]
            mean, std = mean_std(differences)
            per_seed = ", ".join(f"{d * 100:+.2f}" for d in differences)
            wins = sum(d > 0 for d in differences)
            lines.append(
                f"| {READOUT_LABELS[second]} − {READOUT_LABELS[first]} "
                f"| {mean * 100:+.2f} pp | {std * 100:.2f} pp | {per_seed} "
                f"| {wins}/{len(differences)} |"
            )

    checks = [
        merged[s]["phase_uncoupled"]["analytic_check"]
        for s in seeds
        if "analytic_check" in merged[s].get("phase_uncoupled", {})
    ]
    if checks:
        median_error, _ = mean_std(c["phase_error_median_rad"] for c in checks)
        max_error = max(c["phase_error_max_rad"] for c in checks)
        agreement, _ = mean_std(c["prediction_agreement"] for c in checks)
        above, _ = mean_std(c["fraction_error_above_0p1rad"] for c in checks)
        undetermined = sum(c["undetermined_entries"] for c in checks)
        total = sum(c["total_entries"] for c in checks)
        rate_failed, _ = mean_std(c["median_rate_of_failures"] for c in checks)
        rate_matched, _ = mean_std(c["median_rate_of_matches"] for c in checks)
        lines += [
            "",
            "## Solver correctness check against the exact equilibrium",
            "",
            "With K = 0 the energy separates per class and its minimum is known:",
            "φ*_c = atan2(b_c, a_c), cos φ*_c = a_c / √(a_c² + b_c²). The relaxed",
            "phases are compared against that closed form. Entries with a",
            "vanishing field have no determined minimum and are counted, not",
            "scored.",
            "",
            f"- median |Δφ| over seeds: **{median_error:.2e} rad**",
            f"- worst |Δφ| over all seeds: {max_error:.2e} rad",
            f"- fraction of entries with |Δφ| > 0.1 rad: {above:.4f}",
            f"- prediction agreement, numerical vs exact: {agreement:.4f}",
            f"- undetermined (r = 0) entries: {undetermined} / {total}",
            "",
            "The failures are not integration error. Entries that disagree with",
            f"the closed form have a median relaxation rate of {rate_failed:.3f}",
            f"against {rate_matched:.3f} for those that agree: they are the",
            "weak-field, slow-relaxing entries identified in the relaxation",
            "study, which run out of time budget rather than accuracy.",
            "",
        ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, default=Path("../../results/hybrid"))
    args = parser.parse_args()
    write_relaxation_report(
        args.results_dir, args.results_dir / "relaxation_convergence.md"
    )
    write_ablation_report(args.results_dir, args.results_dir / "readout_ablation.md")


if __name__ == "__main__":
    main()
