# Continuous-time echo state network (LPCTESN) Lorenz baseline, compared to the
# discrete tanh-ESN already used in B6. Both forecast Lorenz '63 autonomously and
# report valid prediction time (in Lyapunov times) and NRMSE, so they are
# directly comparable.
#
# Usage:
#   julia --project=. scripts/run_lpctesn_lorenz.jl           # full
#   julia --project=. scripts/run_lpctesn_lorenz.jl --quick   # fast

include(joinpath(@__DIR__, "..", "src", "baselines", "baseline_models.jl"))
include(joinpath(@__DIR__, "..", "src", "baselines", "lpctesn.jl"))
using .BaselineModels, .LPCTESN
using Random, Statistics, Printf

const QUICK = "--quick" in ARGS
const SEEDS = QUICK ? 3 : 8
const NR    = QUICK ? 150 : 300
const DT    = 0.02
const LYAP  = 0.9056        # largest Lyapunov exponent of Lorenz '63

const OUTDIR = joinpath(@__DIR__, "..", "results", "baselines")
const FIGDIR = joinpath(@__DIR__, "..", "results", "figures")
isdir(OUTDIR) || mkpath(OUTDIR)
isdir(FIGDIR) || mkpath(FIGDIR)

data = lorenz_data(T=12000)

ct_valid = Float64[]; ct_nrmse = Float64[]
dc_valid = Float64[]; dc_nrmse = Float64[]
local ct_example
for seed in 1:SEEDS
    ct = lpctesn_lorenz(data; NR=NR, spectral_radius=1.1, gamma=10.0, lambda=0.1,
                        input_scale=0.5, train_len=6000, horizon=3000, rng=Xoshiro(seed))
    dc = esn_lorenz(data; Nr=NR, train_len=6000, horizon=3000, rng=Xoshiro(seed))
    push!(ct_valid, ct.valid_steps); push!(ct_nrmse, ct.nrmse)
    push!(dc_valid, dc.valid_steps); push!(dc_nrmse, dc.nrmse)
    seed == 1 && (global ct_example = ct)
    @printf("  seed %d: LPCTESN valid=%d nrmse=%.3f | discrete-ESN valid=%d nrmse=%.3f\n",
            seed, ct.valid_steps, ct.nrmse, dc.valid_steps, dc.nrmse)
end

lyap(v) = v .* DT .* LYAP
ms(v) = (mean(v), (length(v) > 1 ? std(v) : 0.0))
(ctlv_m, ctlv_s) = ms(lyap(ct_valid)); (dclv_m, dclv_s) = ms(lyap(dc_valid))
(ctn_m, ctn_s) = ms(ct_nrmse); (dcn_m, dcn_s) = ms(dc_nrmse)

open(joinpath(OUTDIR, "lpctesn_lorenz.md"), "w") do io
    println(io, "# LPCTESN vs discrete ESN — Lorenz forecasting\n")
    println(io, "Generated by `scripts/run_lpctesn_lorenz.jl` ", QUICK ? "(quick)" : "", ".")
    println(io, "Reservoir size $NR, $(SEEDS) seeds. Valid time = first step where the ",
                "normalized error exceeds 0.4; reported in Lyapunov times (λ₁=$LYAP).\n")
    println(io, "| Reservoir | Valid time (Lyapunov times) | NRMSE (full horizon) |")
    println(io, "|---|---|---|")
    println(io, @sprintf("| Continuous-time (LPCTESN) | %.2f ± %.2f | %.2f ± %.2f |", ctlv_m, ctlv_s, ctn_m, ctn_s))
    println(io, @sprintf("| Discrete tanh-ESN | %.2f ± %.2f | %.2f ± %.2f |", dclv_m, dclv_s, dcn_m, dcn_s))
end

# figure: LPCTESN forecast (seed 1), zoomed to where it breaks down
using CairoMakie
nshow = min(size(ct_example.truth, 2), max(400, 8 * ct_example.valid_steps))
fig = Figure(size=(900, 640))
Label(fig[0, 1:1], "LPCTESN Lorenz forecast (seed 1)", fontsize=17, font=:bold)
cn = ["x", "y", "z"]; tt = (1:nshow) .* DT
for c in 1:3
    ax = Axis(fig[c, 1], ylabel=cn[c], xlabel=(c == 3 ? "time" : ""))
    lines!(ax, tt, ct_example.truth[c, 1:nshow], color=:black, label="truth")
    lines!(ax, tt, ct_example.pred[c, 1:nshow], color=:crimson, linestyle=:dash, label="LPCTESN")
    vlines!(ax, [ct_example.valid_steps * DT], color=:gray, linestyle=:dot)
    c == 1 && axislegend(ax, position=:rb)
end
ax4 = Axis(fig[4, 1], ylabel="norm. error", xlabel="time")
lines!(ax4, tt, ct_example.err[1:nshow], color=:black)
hlines!(ax4, [0.4], color=:gray, linestyle=:dash)
vlines!(ax4, [ct_example.valid_steps * DT], color=:gray, linestyle=:dot)
save(joinpath(FIGDIR, "lpctesn_lorenz.png"), fig)

println()
@printf("LPCTESN     : valid %.2f ± %.2f Lyap times, NRMSE %.2f\n", ctlv_m, ctlv_s, ctn_m)
@printf("discrete ESN: valid %.2f ± %.2f Lyap times, NRMSE %.2f\n", dclv_m, dclv_s, dcn_m)
println("\nWrote ", joinpath(OUTDIR, "lpctesn_lorenz.md"), " and the figure.")
