# Avalanche-criticality diagnostic for the FHN reservoir, following Beattie
# et al. 2024 (Communications Physics). Tests whether the network reaches
# branching/avalanche criticality (power-law avalanche statistics, branching
# ratio ~ 1) as a function of coupling strength -- the criticality notion that
# paper actually uses, as opposed to the dynamical edge of chaos.
#
# Setup: N excitable FHN oscillators (a>1, quiescent until driven), input to a
# subset of nodes via sparse Poisson spike trains; activity propagates through
# the coupling as cascades. We sweep the coupling strength sigma and measure the
# branching ratio, power-law exponents of avalanche size/duration, and the mean
# network activity (Beattie's phase-transition observable).
#
# Usage:
#   julia --project=. scripts/run_avalanche_criticality.jl           # full
#   julia --project=. scripts/run_avalanche_criticality.jl --quick   # fast

include(joinpath(@__DIR__, "..", "src", "baselines", "fhn_reservoir.jl"))
include(joinpath(@__DIR__, "..", "src", "baselines", "avalanche.jl"))
using .FHNReservoir, .AvalancheCriticality
using Random, Statistics, Printf

const QUICK  = "--quick" in ARGS
const N      = 100                 # FHN oscillators (Beattie used 100)
const NIN    = 20                  # driven nodes (~20%)
const AEXC   = 1.05                # excitable regime (|a|>1, quiescent at rest)
const T      = QUICK ? 1500 : 4000 # integration steps (avalanche statistics)
const RATE   = 0.05                # input spike probability per step
const THRESH = 1.0                 # spike-detection voltage threshold
const BIN    = 2                   # time-bin width for avalanches
const SEEDS  = QUICK ? 2 : 4
const SIGMAS = QUICK ? [0.003, 0.03, 0.3] : [0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0]

const OUTDIR = joinpath(@__DIR__, "..", "results", "baselines")
const FIGDIR = joinpath(@__DIR__, "..", "results", "figures")
isdir(OUTDIR) || mkpath(OUTDIR)
isdir(FIGDIR) || mkpath(FIGDIR)

# sparse Poisson drive to the first NIN nodes; the rest are undriven (0)
function build_drive(seed)
    rng = Xoshiro(seed)
    S = zeros(N, T)
    S[1:NIN, :] .= Float64.(rand(rng, NIN, T) .< RATE)
    return S
end

# one realization -> (sizes, durations, mean_activity)
function avalanche_run(sigma, seed)
    S = build_drive(seed)
    U = fhn_states(S, sigma; seed=seed, a=AEXC)
    sp = detect_spikes(U; thresh=THRESH)
    act = population_activity(sp; bin=BIN)
    sizes, durs = avalanche_stats(act)
    return sizes, durs, mean(act), branching_ratio(act)
end

# pdf of a discrete distribution: (unique values, normalized frequency)
function discrete_pdf(x)
    isempty(x) && return (Float64[], Float64[])
    vals = sort(unique(x))
    n = length(x)
    return (Float64.(vals), [count(==(v), x) / n for v in vals])
end

println("Avalanche-criticality sweep: N=$N excitable FHN (a=$AEXC), $NIN driven, T=$T, $(SEEDS) seeds")
results = Dict{Float64,NamedTuple}()
example_sizes = Dict{Float64,Vector{Int}}()
for sigma in SIGMAS
    allsizes = Int[]; alldurs = Int[]; brs = Float64[]; acts = Float64[]
    for seed in 1:SEEDS
        sizes, durs, act, br = avalanche_run(sigma, seed)
        append!(allsizes, sizes); append!(alldurs, durs)
        push!(brs, br); push!(acts, act)
    end
    results[sigma] = (
        n_av = length(allsizes),
        tau = powerlaw_mle(allsizes; xmin=1),
        alpha = powerlaw_mle(alldurs; xmin=1),
        branch = mean(filter(!isnan, brs)),
        activity = mean(acts),
    )
    example_sizes[sigma] = allsizes
    r = results[sigma]
    @printf("  sigma=%.3f  n_av=%d  branch=%.2f  tau=%.2f  alpha=%.2f  act=%.3f\n",
            sigma, r.n_av, r.branch, r.tau, r.alpha, r.activity)
end

# ----------------------------------------------------------------- report
open(joinpath(OUTDIR, "avalanche_criticality.md"), "w") do io
    println(io, "# Avalanche criticality of the FHN reservoir (Beattie-style)\n")
    println(io, "Generated by `scripts/run_avalanche_criticality.jl` ", QUICK ? "(quick)" : "", ".")
    println(io, "N=$N excitable FHN (a=$AEXC), $NIN driven nodes, T=$T, $(SEEDS) seeds, ",
                "spike threshold $THRESH, bin $BIN.\n")
    println(io, "Branching ratio ~ 1 with power-law exponents (tau~1.5, alpha~2.0) ",
                "indicates avalanche criticality.\n")
    println(io, "| σ | #avalanches | branching ratio | τ (size) | α (dur) | mean activity |")
    println(io, "|---|---|---|---|---|---|")
    for s in SIGMAS
        r = results[s]
        println(io, @sprintf("| %.3f | %d | %.2f | %.2f | %.2f | %.3f |",
                             s, r.n_av, r.branch, r.tau, r.alpha, r.activity))
    end
end

# ----------------------------------------------------------------- figures
using CairoMakie

# pick representative sub/critical/super sigmas by branching ratio
brs = [(s, results[s].branch) for s in SIGMAS]
crit_sigma = SIGMAS[argmin(abs.([results[s].branch - 1 for s in SIGMAS]))]
sub_sigma  = SIGMAS[1]
sup_sigma  = SIGMAS[end]

fig = Figure(size=(960, 380))
Label(fig[0, 1:3], "Avalanche criticality of the FHN reservoir", fontsize=17, font=:bold)

# (a) avalanche size distributions, log-log
ax1 = Axis(fig[1, 1], xscale=log10, yscale=log10, xlabel="avalanche size",
           ylabel="P(size)", title="size distribution")
for (s, col, lab) in ((sub_sigma, :steelblue, "subcritical"),
                      (crit_sigma, :crimson, "critical"),
                      (sup_sigma, :gray40, "supercritical"))
    xv, pv = discrete_pdf(example_sizes[s])
    keep = (xv .> 0) .& (pv .> 0)
    scatter!(ax1, xv[keep], pv[keep], color=col, markersize=6,
             label=@sprintf("σ=%.3f (%s)", s, lab))
end
axislegend(ax1, position=:lb, labelsize=9)

# (b) branching ratio vs sigma
ax2 = Axis(fig[1, 2], xscale=log10, xlabel="coupling σ", ylabel="branching ratio",
           title="branching ratio")
scatterlines!(ax2, SIGMAS, [results[s].branch for s in SIGMAS], color=:black)
hlines!(ax2, [1.0], color=:crimson, linestyle=:dash)

# (c) mean activity vs sigma (Beattie's phase-transition observable)
ax3 = Axis(fig[1, 3], xscale=log10, xlabel="coupling σ", ylabel="mean activity",
           title="network activity")
scatterlines!(ax3, SIGMAS, [results[s].activity for s in SIGMAS], color=:black)

save(joinpath(FIGDIR, "avalanche_criticality.png"), fig)

println("\nWrote:")
println("  ", joinpath(OUTDIR, "avalanche_criticality.md"))
println("  ", joinpath(FIGDIR, "avalanche_criticality.png"))
