# Baseline experiments for the manuscript critique
# (docs/critique_chaotic_oscillator_networks.md).
#
# Produces, with mean +/- std over multiple seeds:
#   - digits  (== sklearn load_digits, 1797x64, 80/20 stratified split)
#   - drybean (13611x16, repeated stratified 5-fold)
# for logistic regression, linear SVM, small MLP, and a tanh-ESN, plus a
# Lorenz-prediction ESN baseline (valid time + NRMSE), and a paired
# Wilcoxon test illustrating the topology-comparison protocol.
#
# Usage:
#   julia --project=. scripts/run_baselines.jl            # full (10 seeds)
#   julia --project=. scripts/run_baselines.jl --quick    # fast smoke (3 seeds)
#
# Outputs go to results/baselines/ and results/figures/.

include(joinpath(@__DIR__, "..", "src", "baselines", "baseline_utils.jl"))
include(joinpath(@__DIR__, "..", "src", "baselines", "baseline_models.jl"))
using .BaselineUtils, .BaselineModels
using Random, Statistics, Printf, DelimitedFiles

const QUICK = "--quick" in ARGS
const NSEEDS = QUICK ? 3 : 10
const EPOCHS = QUICK ? 150 : 400
const NR     = QUICK ? 300 : 500

const OUTDIR = joinpath(@__DIR__, "..", "results", "baselines")
const FIGDIR = joinpath(@__DIR__, "..", "results", "figures")
isdir(OUTDIR) || mkpath(OUTDIR)
isdir(FIGDIR) || mkpath(FIGDIR)

# model name -> (Xtr,Ytr,Xte,classes,rng) -> predicted class labels
function make_runners(classes)
    Dict(
        "logreg"     => (Xtr, Ytr, Xte, rng) -> classes[predict_nn(train_logreg(Xtr, Ytr; epochs=EPOCHS, rng=rng), Xte)],
        "linear_svm" => (Xtr, Ytr, Xte, rng) -> classes[predict_nn(train_linear_svm(Xtr, Ytr; epochs=EPOCHS, rng=rng), Xte)],
        "mlp"        => (Xtr, Ytr, Xte, rng) -> classes[predict_nn(train_mlp(Xtr, Ytr; epochs=EPOCHS, rng=rng), Xte)],
        "tanh_esn"   => (Xtr, Ytr, Xte, rng) -> classes[esn_classify(build_esn(NR, 1; spectral_radius=0.9, rng=rng), Xtr, Ytr, Xte)],
    )
end

const MODELS = ["logreg", "linear_svm", "mlp", "tanh_esn"]

# Run a dataset over many (split, model-init) seeds. `splitter(rng)` returns
# (train_idx, test_idx). Returns Dict(model => (acc, macroF1, weightedF1) arrays)
# and keeps one representative confusion matrix per model (last seed).
function run_dataset(name, X, y, classes, splitter)
    runners = make_runners(classes)
    res = Dict(m => (acc=Float64[], mf1=Float64[], wf1=Float64[]) for m in MODELS)
    confs = Dict{String,Any}()
    for seed in 1:NSEEDS
        rng = Xoshiro(seed)
        tr, te = splitter(rng)
        sc = standardize_fit(X[:, tr])
        Xtr = standardize_apply(X[:, tr], sc)
        Xte = standardize_apply(X[:, te], sc)
        Ytr = onehot(y[tr], classes)
        for m in MODELS
            pred = runners[m](Xtr, Ytr, Xte, rng)
            rep = classification_report(pred, y[te], classes)
            push!(res[m].acc, rep.accuracy)
            push!(res[m].mf1, rep.macro_f1)
            push!(res[m].wf1, rep.weighted_f1)
            confs[m] = rep
        end
        @printf("  [%s] seed %d/%d done\n", name, seed, NSEEDS)
    end
    return res, confs
end

# ------------------------------------------------------------------ datasets
println("Loading data...")
Xd, yd = load_digits()
Xb, yb = load_drybean()
classes_d = sort(unique(yd))
classes_b = sort(unique(yb))

println("Running digits baselines ($(NSEEDS) seeds, 80/20 stratified split)...")
res_d, conf_d = run_dataset("digits", Xd, yd, classes_d,
                            rng -> stratified_split(yd, 0.8; rng=rng))

println("Running drybean baselines ($(NSEEDS) folds, stratified k-fold)...")
# repeated stratified 5-fold gives NSEEDS folds total
let folds = Tuple{Vector{Int},Vector{Int}}[]
    r = 0
    while length(folds) < NSEEDS
        append!(folds, stratified_kfold(yb, 5; rng=Xoshiro(1000 + r)))
        r += 1
    end
    global _bfolds = folds[1:NSEEDS]
end
_bf_counter = Ref(0)
res_b, conf_b = run_dataset("drybean", Xb, yb, classes_b,
                            rng -> (_bf_counter[] += 1; _bfolds[_bf_counter[]]))

# -------------------------------------------------------------------- Lorenz
println("Running Lorenz ESN baseline...")
Ldata = lorenz_data(T=12000)
lor_valid = Float64[]; lor_nrmse = Float64[]
local lor_example
for seed in 1:NSEEDS
    r = esn_lorenz(Ldata; Nr=NR, train_len=6000, horizon=3000, rng=Xoshiro(seed))
    push!(lor_valid, r.valid_steps)
    push!(lor_nrmse, r.nrmse)
    seed == 1 && (global lor_example = r)
end
const LYAP = 0.9056   # largest Lyapunov exponent of Lorenz '63
const DT = 0.02
lyap_times = lor_valid .* DT .* LYAP

# --------------------------------------------------------------- write report
function fmt(v)
    s = summarize(v)
    @sprintf("%.3f ± %.3f", s.mean, s.std)
end

open(joinpath(OUTDIR, "baseline_results.md"), "w") do io
    println(io, "# Baseline results\n")
    println(io, "Generated by `scripts/run_baselines.jl` ", QUICK ? "(quick mode)" : "", ".")
    println(io, "Mean ± std over $(NSEEDS) seeds. ESN reservoir size = $(NR).\n")

    for (title, res) in (("Digits (sklearn load_digits, 1797×64, 10 classes)", res_d),
                         ("Dry Bean (13611×16, 7 classes)", res_b))
        println(io, "## $title\n")
        println(io, "| Model | Accuracy | Macro-F1 | Weighted-F1 |")
        println(io, "|---|---|---|---|")
        for m in MODELS
            println(io, "| $m | $(fmt(res[m].acc)) | $(fmt(res[m].mf1)) | $(fmt(res[m].wf1)) |")
        end
        println(io)
    end

    println(io, "## Lorenz prediction (tanh-ESN)\n")
    println(io, "| Metric | Value |")
    println(io, "|---|---|")
    println(io, "| Valid time (steps) | $(fmt(lor_valid)) |")
    println(io, @sprintf("| Valid time (Lyapunov times) | %.2f ± %.2f |", mean(lyap_times), std(lyap_times)))
    println(io, "| NRMSE over full horizon | $(fmt(lor_nrmse)) |")
    println(io)

    # Wilcoxon example: MLP vs logreg on digits
    w = wilcoxon_signed_rank(res_d["mlp"].acc, res_d["logreg"].acc)
    println(io, "## Paired Wilcoxon signed-rank (protocol demo)\n")
    println(io, @sprintf("MLP vs logistic regression on digits: W=%.1f, z=%.2f, p=%.4f\n", w.W, w.z, w.p))

    # per-class table for drybean (worst-case the critique flags)
    println(io, "## Dry Bean per-class metrics (representative seed, MLP)\n")
    rep = conf_b["mlp"]
    pc = rep.per_class
    println(io, "| Class | Precision | Recall | F1 | Support |")
    println(io, "|---|---|---|---|---|")
    for (i, c) in enumerate(rep.classes)
        println(io, @sprintf("| %s | %.3f | %.3f | %.3f | %d |", c, pc.precision[i], pc.recall[i], pc.f1[i], pc.support[i]))
    end
end

# raw per-seed CSV
open(joinpath(OUTDIR, "baseline_results.csv"), "w") do io
    println(io, "dataset,model,seed,accuracy,macro_f1,weighted_f1")
    for (dname, res) in (("digits", res_d), ("drybean", res_b))
        for m in MODELS, s in 1:NSEEDS
            @printf(io, "%s,%s,%d,%.5f,%.5f,%.5f\n", dname, m, s, res[m].acc[s], res[m].mf1[s], res[m].wf1[s])
        end
    end
end

# ---------------------------------------------------------------- Lorenz fig
using CairoMakie
# zoom to the window where tracking breaks down (valid time is only a few
# Lyapunov times); a 10x-valid window makes the divergence and marker visible.
nshow = min(size(lor_example.truth, 2), max(400, 10 * lor_example.valid_steps))
fig = Figure(size=(900, 700))
Label(fig[0, 1:1], "tanh-ESN Lorenz forecast (seed 1)", fontsize=17, font=:bold)
coordnames = ["x", "y", "z"]
tt = (1:nshow) .* DT
for c in 1:3
    ax = Axis(fig[c, 1], ylabel=coordnames[c], xlabel=(c == 3 ? "time" : ""))
    lines!(ax, tt, lor_example.truth[c, 1:nshow], color=:black, label="truth")
    lines!(ax, tt, lor_example.pred[c, 1:nshow], color=:crimson, linestyle=:dash, label="ESN")
    vlines!(ax, [lor_example.valid_steps * DT], color=:gray, linestyle=:dot)
    c == 1 && axislegend(ax, position=:rb)
end
ax4 = Axis(fig[4, 1], ylabel="norm. error", xlabel="time")
lines!(ax4, (1:nshow) .* DT, lor_example.err[1:nshow], color=:black)
hlines!(ax4, [0.4], color=:gray, linestyle=:dash)
vlines!(ax4, [lor_example.valid_steps * DT], color=:gray, linestyle=:dot)
text!(ax4, lor_example.valid_steps * DT, 0.42;
      text="valid ≈ $(round(lor_example.valid_steps*DT*LYAP, digits=1)) Lyap. times",
      align=(:left, :bottom), fontsize=11)
save(joinpath(FIGDIR, "lorenz_esn_prediction.png"), fig)

println("\nWrote:")
println("  ", joinpath(OUTDIR, "baseline_results.md"))
println("  ", joinpath(OUTDIR, "baseline_results.csv"))
println("  ", joinpath(FIGDIR, "lorenz_esn_prediction.png"))
